version: '3'

services:
  protea-api-server:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/workspace
    ports:
      - "8000:8000"
    tty: true
